### ISSUE TITLE
更新问题

### ISSUE THREAD

**Issue by Maple-SF** [nonwill/goldendict#14]
在软件内检查更新，只能下载到图标，下不到更新内容

**Comment by nonwill** [comment]
感谢反馈。
较老的版本存在这个问题，在更新下载时候未处理url重定向问题，下载下来的文件实际上是一个html文件（内含url重定向信息）。这种情况下需要手动下载升级包更新。最新的基础包和更新包请从https://nonwill.github.io/post/goldendict/获取，最新版本的升级包托管在github的release页面：https://github.com/nonwill/nwDeployed/releases/。

**Comment by Maple-SF** [comment]
好的，谢谢



------------------&nbsp;原始邮件&nbsp;------------------
发件人: "nonwill"<notifications@github.com&gt;; 
发送时间: 2020年6月2日(星期二) 下午2:21
收件人: "nonwill/goldendict"<goldendict@noreply.github.com&gt;; 
抄送: "那時花開"<758380530@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [nonwill/goldendict] 更新问题 (#14)





 
感谢反馈。
 较老的版本存在这个问题，在更新下载时候未处理url重定向问题，下载下来的文件实际上是一个html文件（内含url重定向信息）。这种情况下需要手动下载升级包更新。最新的基础包和更新包请从https://nonwill.github.io/post/goldendict/获取，最新版本的升级包托管在github的release页面：https://github.com/nonwill/nwDeployed/releases/。

**Comment by Maple-SF** [comment]
Hello，

现在点击更新不会跳出对话框，完全没有反应。


祝好




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "nonwill"<notifications@github.com&gt;; 
发送时间: 2020年6月2日(星期二) 下午2:21
收件人: "nonwill/goldendict"<goldendict@noreply.github.com&gt;; 
抄送: "那時花開"<758380530@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [nonwill/goldendict] 更新问题 (#14)





 
感谢反馈。
 较老的版本存在这个问题，在更新下载时候未处理url重定向问题，下载下来的文件实际上是一个html文件（内含url重定向信息）。这种情况下需要手动下载升级包更新。最新的基础包和更新包请从https://nonwill.github.io/post/goldendict/获取，最新版本的升级包托管在github的release页面：https://github.com/nonwill/nwDeployed/releases/。

**Comment by nonwill** [comment]
你好，
      感谢支持。
      点击更新不会跳出对话框，这个问题最大的原因可能是github page网站访问受限造成的，在读取更新信息时候访问被挂起了。请确认是否已经屏蔽了对该网站的访问，或是使用了代理但不支持该网站的访问，亦或是网络运营商对该网站的访问有什么限制...，最简单的方法就是在同样网络环境下使用其它网页浏览器对github page进行访问，看是否能有效的打开所访问的页面。如果https://nonwill.github.io/post/goldendict/ 页面能够正常访问，那么更新信息的读取应该也是没有问题的。
   祝
 工作顺利/学业高成！
________________________________
发件人: Maple-SF <notifications@github.com>
发送时间: 2020年6月13日 8:29
收件人: nonwill/goldendict <goldendict@noreply.github.com>
抄送: nonwill <nonwill@hotmail.com>; State change <state_change@noreply.github.com>
主题: Re: [nonwill/goldendict] 更新问题 (#14)


Hello，

现在点击更新不会跳出对话框，完全没有反应。


祝好




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "nonwill"<notifications@github.com&gt;;
发送时间: 2020年6月2日(星期二) 下午2:21
收件人: "nonwill/goldendict"<goldendict@noreply.github.com&gt;;
抄送: "那r花_"<758380530@qq.com&gt;; "Author"<author@noreply.github.com&gt;;
主题: Re: [nonwill/goldendict] 更新问题 (#14)






感谢反馈。
较老的版本存在这个问题，在更新下载时候未处理url重定向问题，下载下来的文件实际上是一个html文件（内含url重定向信息）。这种情况下需要手动下载升级包更新。最新的基础包和更新包请从https://nonwill.github.io/post/goldendict/获取，最新版本的升级包托管在github的release页面：https://github.com/nonwill/nwDeployed/releases/。

―
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.

―

**Comment by Maple-SF** [comment]
Hello，


谢谢指教！


又试了几次打开了窗口，但是提示不可以下载。那个网页可以打开的。用链接下载了，速度超级慢，国内的Github，哎。。。


祝好！




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"nonwill"<notifications@github.com&gt;;
发送时间:&nbsp;2020年6月13日(星期六) 中午11:21
收件人:&nbsp;"nonwill/goldendict"<goldendict@noreply.github.com&gt;;
抄送:&nbsp;"那時花開"<758380530@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [nonwill/goldendict] 更新问题 (#14)





 你好， 
       感谢支持。 
       点击更新不会跳出对话框，这个问题最大的原因可能是github page网站访问受限造成的，在读取更新信息时候访问被挂起了。请确认是否已经屏蔽了对该网站的访问，或是使用了代理但不支持该网站的访问，亦或是网络运营商对该网站的访问有什么限制...，最简单的方法就是在同样网络环境下使用其它网页浏览器对github page进行访问，看是否能有效的打开所访问的页面。如果https://nonwill.github.io/post/goldendict/ 页面能够正常访问，那么更新信息的读取应该也是没有问题的。 
    祝 
  工作顺利/学业高成！ 
 ________________________________ 
 发件人: Maple-SF <notifications@github.com&gt; 
 发送时间: 2020年6月13日 8:29 
 收件人: nonwill/goldendict <goldendict@noreply.github.com&gt; 
 抄送: nonwill <nonwill@hotmail.com&gt;; State change <state_change@noreply.github.com&gt; 
 主题: Re: [nonwill/goldendict] 更新问题 (#14) 
 
 
 Hello， 
 
 现在点击更新不会跳出对话框，完全没有反应。 
 
 
 祝好 
 
 
 
 
 ------------------&amp;nbsp;原始邮件&amp;nbsp;------------------ 
 发件人: "nonwill"<notifications@github.com&amp;gt;; 
 发送时间: 2020年6月2日(星期二) 下午2:21 
 收件人: "nonwill/goldendict"<goldendict@noreply.github.com&amp;gt;; 
 抄送: "那•r花_"<758380530@qq.com&amp;gt;; "Author"<author@noreply.github.com&amp;gt;; 
 主题: Re: [nonwill/goldendict] 更新问题 (#14) 
 
 
 
 
 
 
 感谢反馈。 
 较老的版本存在这个问题，在更新下载时候未处理url重定向问题，下载下来的文件实际上是一个html文件（内含url重定向信息）。这种情况下需要手动下载升级包更新。最新的基础包和更新包请从https://nonwill.github.io/post/goldendict/获取，最新版本的升级包托管在github的release页面：https://github.com/nonwill/nwDeployed/releases/。 
 
 ― 
 You are receiving this because you authored the thread. 
 Reply to this email directly, view it on GitHub, or unsubscribe. 
 
 ―
